/* Heat Map state server — authenticated reads, owner-only writes. */
const fs = require('fs');
const path = require('path');
const http = require('http');
const crypto = require('crypto');
const express = require('express');
const cors = require('cors');
const compression = require('compression');

// ---------------------------------------------------------------------------
// Config — read from .env without an additional dotenv dependency.
// ---------------------------------------------------------------------------
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8')
    .split('\n')
    .forEach(line => {
      const m = line.match(/^([^#=\s][^=]*)=(.*)$/);
      if (m) process.env[m[1].trim()] = m[2].trim();
    });
}

const PORT = parseInt(process.env.PORT || '3001', 10);
const API_KEY = process.env.API_KEY || '';
const SESSION_SECRET = process.env.SESSION_SECRET || '';
const DATABASE_URL = process.env.DATABASE_URL || '';
const ORIGINS = (process.env.ALLOWED_ORIGINS || '')
  .split(',').map(s => s.trim()).filter(Boolean);
const SESSION_TTL_SEC = 8 * 60 * 60;
const AUTH_ROLES = new Set(['admin', 'comdep', 'other', 'kg']);
const STATE_FILE = path.join(__dirname, 'state.json');

function loadAuthUsers() {
  const raw = process.env.AUTH_USERS_JSON || '';
  if (!raw) return new Map();
  try {
    const parsed = JSON.parse(raw);
    const users = new Map();
    for (const [username, value] of Object.entries(parsed)) {
      const u = username.trim().toLowerCase();
      if (!u || !value || typeof value.passwordHash !== 'string' || !AUTH_ROLES.has(value.role)) continue;
      users.set(u, { username: u, role: value.role, passwordHash: value.passwordHash });
    }
    return users;
  } catch (e) {
    console.error('Invalid AUTH_USERS_JSON:', e.message);
    return new Map();
  }
}

const AUTH_USERS = loadAuthUsers();
if (!API_KEY || API_KEY === 'change_me_to_something_secret') {
  console.warn('\nWARNING: API_KEY is missing or is the default placeholder.');
  console.warn('Owner writes are disabled until a strong API_KEY is configured.\n');
}
if (!SESSION_SECRET) {
  console.warn('WARNING: SESSION_SECRET is missing. Login is disabled until it is configured.');
}
if (!AUTH_USERS.size) {
  console.warn('WARNING: AUTH_USERS_JSON is missing or invalid. Login is disabled until it is configured.');
}

// ---------------------------------------------------------------------------
// Password and session helpers.
// Password hashes are scrypt$N$r$p$salt$hexHash strings generated by
// create-password-hash.js. Plain-text passwords never enter the repository.
// ---------------------------------------------------------------------------
function parsePasswordHash(encoded) {
  const parts = String(encoded || '').split('$');
  if (parts.length !== 6 || parts[0] !== 'scrypt') return null;
  const [, n, r, p, salt, hex] = parts;
  const N = Number(n), R = Number(r), P = Number(p);
  if (!Number.isInteger(N) || !Number.isInteger(R) || !Number.isInteger(P) || !salt || !/^[0-9a-f]+$/i.test(hex)) return null;
  return { N, R, P, salt, hex };
}

function verifyPassword(password, encoded) {
  const cfg = parsePasswordHash(encoded);
  if (!cfg) return false;
  try {
    const actual = crypto.scryptSync(String(password || ''), cfg.salt, cfg.hex.length / 2, {
      N: cfg.N, r: cfg.R, p: cfg.P, maxmem: 64 * 1024 * 1024,
    });
    const expected = Buffer.from(cfg.hex, 'hex');
    return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
  } catch (_) {
    return false;
  }
}

function b64url(value) {
  return Buffer.from(value).toString('base64url');
}

function signSession(payload) {
  return crypto.createHmac('sha256', SESSION_SECRET).update(payload).digest('base64url');
}

function createSession(user) {
  const payload = b64url(JSON.stringify({
    u: user.username,
    role: user.role,
    exp: Math.floor(Date.now() / 1000) + SESSION_TTL_SEC,
  }));
  return payload + '.' + signSession(payload);
}

function readCookie(req, name) {
  const raw = req.headers.cookie || '';
  for (const part of raw.split(';')) {
    const i = part.indexOf('=');
    if (i < 0) continue;
    if (part.slice(0, i).trim() === name) {
      try { return decodeURIComponent(part.slice(i + 1).trim()); } catch (_) { return ''; }
    }
  }
  return '';
}

function readBearer(req) {
  const header = String(req.headers.authorization || '');
  return /^Bearer\s+/i.test(header) ? header.slice(7).trim() : '';
}

function verifySessionToken(token) {
  if (!SESSION_SECRET || !token) return null;
  const dot = token.indexOf('.');
  if (dot <= 0) return null;
  const payload = token.slice(0, dot), signature = token.slice(dot + 1);
  const expected = signSession(payload);
  const a = Buffer.from(signature), b = Buffer.from(expected);
  if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null;
  try {
    const data = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8'));
    if (!data.u || !data.role || !Number.isFinite(data.exp) || data.exp <= Date.now() / 1000) return null;
    const user = AUTH_USERS.get(String(data.u).toLowerCase());
    if (!user || user.role !== data.role) return null;
    return { username: user.username, role: user.role };
  } catch (_) {
    return null;
  }
}

function readSession(req) {
  // Prefer the explicit bearer token for GitHub Pages ↔ Render, then fall back
  // to the HttpOnly cookie for same-site or browsers that retain third-party cookies.
  return verifySessionToken(readBearer(req)) || verifySessionToken(readCookie(req, 'hm_session'));
}

function isHttps(req) {
  return req.secure || req.headers['x-forwarded-proto'] === 'https' || process.env.NODE_ENV === 'production';
}

function setSessionCookie(req, res, token) {
  const secure = isHttps(req);
  res.setHeader('Set-Cookie', `hm_session=${encodeURIComponent(token)}; Max-Age=${SESSION_TTL_SEC}; Path=/; HttpOnly; SameSite=${secure ? 'None' : 'Lax'}${secure ? '; Secure' : ''}`);
}

function clearSessionCookie(req, res) {
  const secure = isHttps(req);
  res.setHeader('Set-Cookie', `hm_session=; Max-Age=0; Path=/; HttpOnly; SameSite=${secure ? 'None' : 'Lax'}${secure ? '; Secure' : ''}`);
}

function noStore(res) {
  res.setHeader('Cache-Control', 'no-store');
}

// ---------------------------------------------------------------------------
// Storage — PostgreSQL (persistent) or atomic file fallback.
// ---------------------------------------------------------------------------
let db = null;

async function initDb() {
  if (!DATABASE_URL) return;
  const { Client } = require('pg');
  db = new Client({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } });
  await db.connect();
  await db.query(`
    CREATE TABLE IF NOT EXISTS app_state (
      key TEXT PRIMARY KEY,
      json TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )
  `);
  console.log('PostgreSQL connected — state will persist across restarts');
}

const MAPS = ['comdep', 'other', 'kg'];
function mapKey(req) {
  const m = (req.query.map || '').toString();
  return MAPS.includes(m) ? m : null;
}
function stateFileFor(key) {
  return key === 'main' ? STATE_FILE : path.join(__dirname, `state.${key}.json`);
}

async function readState(key) {
  if (db) {
    try {
      const r = await db.query('SELECT json FROM app_state WHERE key = $1', [key]);
      if (r.rows.length === 0) return null;
      return JSON.parse(r.rows[0].json);
    } catch (e) {
      console.error('DB read error:', e.message);
      return null;
    }
  }
  try {
    const f = stateFileFor(key);
    if (fs.existsSync(f)) return JSON.parse(fs.readFileSync(f, 'utf8'));
  } catch (e) {
    console.error('Failed to read state file:', e.message);
  }
  return null;
}

async function writeState(key, data) {
  const json = JSON.stringify(data);
  if (db) {
    await db.query(
      `INSERT INTO app_state (key, json, updated_at)
       VALUES ($1, $2, $3)
       ON CONFLICT (key) DO UPDATE SET json = $2, updated_at = $3`,
      [key, json, new Date().toISOString()]
    );
    return;
  }
  const f = stateFileFor(key), tmp = f + '.tmp';
  fs.writeFileSync(tmp, json, 'utf8');
  fs.renameSync(tmp, f);
}

function verifyKey(req) {
  if (!API_KEY) return false; // fail closed: no configured key means no writes
  const header = req.headers['x-api-key'] || '';
  return header === API_KEY;
}

function requireSession(req, res, next) {
  const user = readSession(req);
  if (!user) {
    noStore(res);
    return res.status(401).json({ error: 'Authentication required' });
  }
  req.user = user;
  next();
}

function requireAdmin(req, res, next) {
  if (!req.user || req.user.role !== 'admin') return res.status(403).json({ error: 'Owner access required' });
  next();
}

function requireMapAccess(req, res, next) {
  const map = mapKey(req);
  if (!map) return res.status(400).json({ error: 'Invalid map' });
  if (req.user.role !== 'admin' && req.user.role !== map) return res.status(403).json({ error: 'Map access denied' });
  req.map = map;
  next();
}

// ---------------------------------------------------------------------------
// App and middleware.
// ---------------------------------------------------------------------------
const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use((_req, res, next) => {
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('Referrer-Policy', 'no-referrer');
  next();
});
app.use(cors({
  origin: (origin, cb) => {
    if (!origin) return cb(null, true);
    if (ORIGINS.length === 0 || ORIGINS.includes(origin)) return cb(null, origin);
    cb(new Error(`CORS: origin ${origin} not allowed`));
  },
  credentials: true,
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'X-API-Key', 'Content-Encoding'],
}));
app.use(compression());

// Login has a small body limit and is the only POST route allowed before the
// owner-key middleware. Logout only clears the browser cookie.
app.post('/auth/login', express.json({ limit: '32kb' }), (req, res) => {
  noStore(res);
  const username = String(req.body && req.body.username || '').trim().toLowerCase();
  const password = String(req.body && req.body.password || '');
  const user = AUTH_USERS.get(username);
  if (!user || !SESSION_SECRET || !verifyPassword(password, user.passwordHash)) {
    return res.status(401).json({ error: 'Invalid username or password' });
  }
  const token = createSession(user);
  setSessionCookie(req, res, token);
  // The signed token is short-lived and the client keeps it only in sessionStorage
  // as a fallback for browsers that block the cross-site HttpOnly cookie.
  res.json({ ok: true, username: user.username, role: user.role, token, expiresIn: SESSION_TTL_SEC });
});

app.post('/auth/logout', (req, res) => {
  noStore(res);
  clearSessionCookie(req, res);
  res.json({ ok: true });
});

app.get('/auth/me', requireSession, (req, res) => {
  noStore(res);
  res.json({ ok: true, username: req.user.username, role: req.user.role });
});

// Check the owner key before parsing multi-megabyte state bodies.
app.use((req, res, next) => {
  if (req.method !== 'POST') return next();
  if (req.path === '/auth/login' || req.path === '/auth/logout') return next();
  if (verifyKey(req)) return next();
  res.status(401).json({ error: 'Invalid or missing X-API-Key header' });
});
app.use(express.json({ limit: '50mb' }));

app.get('/health', (_req, res) => {
  res.json({
    ok: true,
    ts: new Date().toISOString(),
    storage: db ? 'postgresql' : 'file',
    api: 3,
    authConfigured: Boolean(SESSION_SECRET && AUTH_USERS.size),
    writeAuthConfigured: Boolean(API_KEY),
  });
});

// All data reads now require a valid server-side session.
app.get('/data', requireSession, async (_req, res) => {
  noStore(res);
  const data = await readState('dataset');
  if (!data) return res.json({ empty: true });
  res.json(data);
});

app.post('/data', requireSession, requireAdmin, async (req, res) => {
  noStore(res);
  const body = req.body;
  if (!body || body._app !== 'hm-data') {
    return res.status(400).json({ error: 'Invalid dataset object (missing _app: hm-data marker)' });
  }
  body._savedAt = new Date().toISOString();
  try {
    await writeState('dataset', body);
    res.json({ ok: true, savedAt: body._savedAt });
  } catch (e) {
    console.error('Dataset write error:', e.message);
    res.status(500).json({ error: 'Failed to write dataset' });
  }
});

app.get('/state', requireSession, requireMapAccess, async (req, res) => {
  noStore(res);
  const state = await readState(req.map);
  if (!state) return res.json({ empty: true });
  res.json(state);
});

app.post('/state', requireSession, requireAdmin, requireMapAccess, async (req, res) => {
  noStore(res);
  const body = req.body;
  if (!body || body._app !== 'hm-br') {
    return res.status(400).json({ error: 'Invalid state object (missing _app marker)' });
  }
  body._savedAt = new Date().toISOString();
  try {
    await writeState(req.map, body);
    res.json({ ok: true, savedAt: body._savedAt });
  } catch (e) {
    console.error('Write error:', e.message);
    res.status(500).json({ error: 'Failed to write state' });
  }
});

const server = http.createServer(app);
initDb()
  .catch(e => {
    console.error('Failed to connect to PostgreSQL, falling back to file storage:', e.message);
    db = null;
  })
  .then(() => {
    server.listen(PORT, () => {
      console.log(`\nHeat Map state server running on port ${PORT}`);
      console.log(`Storage: ${db ? 'PostgreSQL' : 'File (ephemeral fallback)'}`);
      console.log(`GET  http://localhost:${PORT}/health`);
      console.log(`POST http://localhost:${PORT}/auth/login`);
    });
  });

function shutdown() {
  if (db) db.end();
  server.close(() => process.exit(0));
}
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);
